//
//  PodcastsRouter.swift
//  mobile-coding-challenge
//
//  Created by Navneet Singh Gill on 2023-05-03.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol PodcastsRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol PodcastsDataPassing
{
  var dataStore: PodcastsDataStore? { get }
}

class PodcastsRouter: NSObject, PodcastsRoutingLogic, PodcastsDataPassing
{
    weak var viewController: PodcastsViewController?
    var dataStore: PodcastsDataStore?
    
    // MARK: Routing
    
    func routePodcastsVCToPodcastDetailsVC(segue: UIStoryboardSegue?)
    {
      if let segue = segue {
        let destinationVC = segue.destination as! PodcastDetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataTo(source: dataStore!, destination: &destinationDS)
      } else {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "PodcastDetailViewController") as! PodcastDetailViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataTo(source: dataStore!, destination: &destinationDS)
        navigateTo(source: viewController!, destination: destinationVC)
      }
    }
    
    // MARK: Navigation
    
    func navigateTo(source: PodcastsViewController, destination: PodcastDetailViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataTo(source: PodcastsDataStore, destination: inout PodcastDetailDataStore)
    {
        destination.podcast = source.podcast
    }
}
