//
//  PodcastsInteractor.swift
//  mobile-coding-challenge
//
//  Created by Navneet Singh Gill on 2023-05-03.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PodcastsBusinessLogic
{
    func getBestPodcasts(request: Podcasts.GetBestPodcasts.Request)
}

protocol PodcastsDataStore
{
    var podcast: Podcast? { get set }
}

class PodcastsInteractor: PodcastsBusinessLogic, PodcastsDataStore
{
    var podcast: Podcast?
    
    var presenter: PodcastsPresentationLogic?
    var worker: PodcastsWorker?
    
    // MARK: APIs
    
    func getBestPodcasts(request: Podcasts.GetBestPodcasts.Request)
    {
        worker = PodcastsWorker()
        worker?.getBestPodcasts(request: request, completionBlock: { [weak self] response, customError in
            self?.presenter?.presentBestPodcasts(response: response, error: customError)
        })
        
    }
}
