//
//  PodcastsModels.swift
//  mobile-coding-challenge
//
//  Created by Navneet Singh Gill on 2023-05-03.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Podcasts
{
    // MARK: Use cases
  
    enum GetBestPodcasts {
      
        struct Request {
            var genreID: String
            var page: String
            var region: String
        }
      
        struct Response {
          let id: String
          let name: String
          let total: String
          let hasNext: Bool
          let podcasts: [Podcast]
          let parentID: Int
          let pageNumber: Int
          let nextPageNumber: Int
          let previousPageNumber: Int
      }
      
      struct ViewModelSuccess {
          let podcasts: [Podcast]
      }
        
      struct ViewModelFailure {
          let error: String
      }
      
    }
}
