//
//  PodcastsViewController.swift
//  mobile-coding-challenge
//
//  Created by Navneet Singh Gill on 2023-05-03.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PodcastsDisplayLogic: class
{
  func displaySomething(viewModel: Podcasts.Something.ViewModel)
}

class PodcastsViewController: UIViewController, PodcastsDisplayLogic
{
    
    @IBOutlet weak var tableView: UITableView!
    
  var interactor: PodcastsBusinessLogic?
  var router: (NSObjectProtocol & PodcastsRoutingLogic & PodcastsDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = PodcastsInteractor()
    let presenter = PodcastsPresenter()
    let router = PodcastsRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
    showTheBestPodcasts()
  }
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
  
  func showTheBestPodcasts()
  {
    let request = Podcasts.GetBestPodcasts.Request()
    interactor?.doSomething(request: request)
  }
  
  func displaySomething(viewModel: Podcasts.Something.ViewModel)
  {
    //nameTextField.text = viewModel.name
  }
}

extension PodcastsViewController: UITableViewDelegate {
    
}

extension PodcastsViewController: UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        return UITableViewCell()
    }
    
}
