//
//  PodcastDetailPresenter.swift
//  mobile-coding-challenge
//
//  Created by Navneet Singh Gill on 2023-05-04.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PodcastDetailPresentationLogic
{
  func presentSomething(response: PodcastDetail.Something.Response)
}

class PodcastDetailPresenter: PodcastDetailPresentationLogic
{
  weak var viewController: PodcastDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: PodcastDetail.Something.Response)
  {
    let viewModel = PodcastDetail.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
