//
//  PodcastDetailInteractor.swift
//  mobile-coding-challenge
//
//  Created by Navneet Singh Gill on 2023-05-04.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PodcastDetailBusinessLogic
{
    func doSomething(request: PodcastDetail.Something.Request)
}

protocol PodcastDetailDataStore
{
    var podcast: Podcast? { get set }
}

class PodcastDetailInteractor: PodcastDetailBusinessLogic, PodcastDetailDataStore
{
    var podcast: Podcast?
    
    var presenter: PodcastDetailPresentationLogic?
    var worker: PodcastDetailWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: PodcastDetail.Something.Request)
    {
        worker = PodcastDetailWorker()
        worker?.doSomeWork()
        
        let response = PodcastDetail.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
