//
//  PodcastDetailViewController.swift
//  mobile-coding-challenge
//
//  Created by Navneet Singh Gill on 2023-05-04.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PodcastDetailDisplayLogic: AnyObject {
    func displaySomething(viewModel: PodcastDetail.Something.ViewModel)
}

struct PodcastDetailViewControllerConstants {
    static let thumbnailImageViewCornerRadius: CGFloat = 20
    static let favouriteButtonCornerRadius: CGFloat = 10
}

struct PodcastDetailViewControllerThemeConstants {
    static let headingFontSize: CGFloat = 23
    static let subheadingFontSize: CGFloat = 19
}

class PodcastDetailViewController: UIViewController, PodcastDetailDisplayLogic {
    
    @IBOutlet weak var titleLabel: UILabel!
    @IBOutlet weak var publisherNameLabel: UILabel!
    @IBOutlet weak var descriptionLabel: UILabel!
    
    @IBOutlet weak var thumbnailImageView: ImageDownloaderImageView!
    
    @IBOutlet weak var favouriteButton: UIButton!
    @IBOutlet weak var backButton: UIButton!
    
    var podcast: Podcast?
    
    weak var delegate: PodcastsViewControllerDelegate?
    
    var interactor: PodcastDetailBusinessLogic?
    var router: (NSObjectProtocol & PodcastDetailRoutingLogic & PodcastDetailDataPassing)?
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = PodcastDetailInteractor()
        let presenter = PodcastDetailPresenter()
        let router = PodcastDetailRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        loadPodcast()
        setUI()
    }
    
    //MARK: Private methods
    
    func loadPodcast() {
        if let podcast = podcast {
            titleLabel.text = podcast.title
            publisherNameLabel.text = podcast.name
            descriptionLabel.text = podcast.description
            
            if let url = URL(string: podcast.thumbNailUrl) {
                thumbnailImageView.load(url: url)
            }
        }
    }
    
    func setUI() {
        backButton.setImage(UIImage(systemName: "chevron.backward"), for: .normal)
        thumbnailImageView.layer.cornerRadius = PodcastDetailViewControllerConstants.thumbnailImageViewCornerRadius
        
        titleLabel.font = UIFont.systemFont(ofSize: PodcastDetailViewControllerThemeConstants.headingFontSize)
        publisherNameLabel.font = UIFont.italicSystemFont(ofSize: PodcastDetailViewControllerThemeConstants.subheadingFontSize)
        
        favouriteButton.backgroundColor = .red
        favouriteButton.layer.cornerRadius = PodcastDetailViewControllerConstants.favouriteButtonCornerRadius
        setFavourite(isFavourite: podcast?.isFavourite ?? false)
    }
    
    func setFavourite(isFavourite: Bool) {
        if isFavourite {
            favouriteButton.setTitle("Favourited", for: .normal)
        } else {
            favouriteButton.setTitle("Favourite", for: .normal)
        }
    }
    
    //MARK: Action methods
    
    @IBAction func backButtonTouchUpInside() {
        if let podcast = podcast {
            delegate?.updateFavouriteIn(podcast: podcast)
        }
        self.dismiss(animated: true)
    }
    
    @IBAction func favouriteButtonTouchUpInside() {
        if var newPodcast = podcast {
            newPodcast.isFavourite = !newPodcast.isFavourite
            setFavourite(isFavourite: newPodcast.isFavourite)
            
            podcast = newPodcast
        }
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething()
    {
        let request = PodcastDetail.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: PodcastDetail.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
}
