//
//  PodcastsPresenter.swift
//  mobile-coding-challenge
//
//  Created by Navneet Singh Gill on 2023-05-03.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PodcastsPresentationLogic
{
  func presentSomething(response: Podcasts.Something.Response)
}

class PodcastsPresenter: PodcastsPresentationLogic
{
  weak var viewController: PodcastsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Podcasts.Something.Response)
  {
    let viewModel = Podcasts.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
