//
//  PodcastsInteractor.swift
//  mobile-coding-challenge
//
//  Created by Navneet Singh Gill on 2023-05-03.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PodcastsBusinessLogic
{
  func doSomething(request: Podcasts.Something.Request)
}

protocol PodcastsDataStore
{
  //var name: String { get set }
}

class PodcastsInteractor: PodcastsBusinessLogic, PodcastsDataStore
{
  var presenter: PodcastsPresentationLogic?
  var worker: PodcastsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Podcasts.Something.Request)
  {
    worker = PodcastsWorker()
    worker?.doSomeWork()
    
    let response = Podcasts.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
